### ISSUE TITLE
link for prebuilt JARs does not work

### ISSUE THREAD

**Issue by ingenthr** [jdbc-json/jdbc-cb#17] opened 2016-01-22 23:26 UTC
The README has a link for prebuilt .jar files, but doesn't seem to respond.

**Comment by arun-gupta** [comment] 2016-01-22 23:57
Duplicate of #15

**Comment by j-larson** [comment] 2016-01-23 00:08
Yeah, sorry about that. I've removed the link, so other people don't stumble over it.

I'll replace it with instructions for downloading from the Maven Repo when that's available.

**Comment by j-larson** [comment] 2016-02-25 14:09
Jar is available from Maven Central.

**Closed as completed by j-larson** 2016-02-25 14:09 UTC
